# Basic Site Settings
title: Saad Labyad
logo: /assets/img/saad_labyad_profile.jpg
description: PhD candidate in Mathematics, University of Oxford
url: https://saadlabyad.github.io/
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jekyll-theme-minimal
